line-length = 130
indent-width = 4

[format]
quote-style = "double"
indent-style = "tab"

[lint]
ignore = ["E741", "F403"]

[lint.isort]
section-order = ["third-party", "local-folder"]
known-local-folder = ["azlassets"]
